[[share]]
name = 'alias'
to = '~/.share/alias'

[[share]]
name = 'env'
to = '~/.share/env'

[[alacritty]]
name = '.alacritty.yml'
to = '~/.alacritty.yml'

# [[bash]]
# name = '.bash_profile'
# to = '~/.bash_profile'

# [[bash]]
# name = '.bash_login'
# to = '~/.bash_login'

[[bash]]  # and sh, ksh, etc.
name = '.profile'
to = '~/.profile'

[[bash]]
name = '.bashrc'
to = '~/.bashrc'

# [[bash]]
# name = '.bash_logout'
# to = '~/.bash_logout'

[[git]]
name = '.gitconfig'
to = '~/.gitconfig'

[[pip]]
name = 'pip.conf'
to = '~/.config/pip/pip.conf'

[[yapf]]
name = '.style.yapf'
to = '~/.style.yapf'

# [[zsh]]
# name = '.zshenv'
# to = '~/.zshenv'

# [[zsh]]
# name = '.zprofile'
# to = '~/.zprofile'

# [[zsh]]
# name = '.zlogin'
# to = '~/.zlogin'

[[zsh]]
name = '.zshrc'
to = '~/.zshrc'

# [[zsh]]
# name = '.zlogout'
# to = '~/.zlogout'
